-- One-shot production schema sync (idempotent-ish)
-- Generated by adapting `prisma migrate diff --from-config-datasource --to-schema prisma/schema.prisma --script`
-- Goal: make prod match `prisma/schema.prisma` in a single migration.
--
-- WARNING: This migration contains DESTRUCTIVE operations (DROP COLUMN).
-- Run with a Neon DIRECT (non-pooler) URL and ensure you have a backup.

-- -----------------------------
-- Helper: conditional constraint rename
-- -----------------------------
DO $$
BEGIN
  -- Artifact primary key
  IF to_regclass('"Artifact"') IS NOT NULL
     AND EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'artifact_pkey')
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Artifact_pkey') THEN
    ALTER TABLE "Artifact" RENAME CONSTRAINT "artifact_pkey" TO "Artifact_pkey";
  END IF;

  -- ArtifactEdge primary key
  IF to_regclass('"ArtifactEdge"') IS NOT NULL
     AND EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'artifact_edge_pkey')
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ArtifactEdge_pkey') THEN
    ALTER TABLE "ArtifactEdge" RENAME CONSTRAINT "artifact_edge_pkey" TO "ArtifactEdge_pkey";
  END IF;

  -- ArtifactEmbedding primary key
  IF to_regclass('"ArtifactEmbedding"') IS NOT NULL
     AND EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'artifact_embedding_pkey')
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ArtifactEmbedding_pkey') THEN
    ALTER TABLE "ArtifactEmbedding" RENAME CONSTRAINT "artifact_embedding_pkey" TO "ArtifactEmbedding_pkey";
  END IF;

  -- BibleReadingProgress primary key
  IF to_regclass('"BibleReadingProgress"') IS NOT NULL
     AND EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'bible_reading_progress_pkey')
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'BibleReadingProgress_pkey') THEN
    ALTER TABLE "BibleReadingProgress" RENAME CONSTRAINT "bible_reading_progress_pkey" TO "BibleReadingProgress_pkey";
  END IF;

  -- BibleReadingSession primary key
  IF to_regclass('"BibleReadingSession"') IS NOT NULL
     AND EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'bible_reading_session_pkey')
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'BibleReadingSession_pkey') THEN
    ALTER TABLE "BibleReadingSession" RENAME CONSTRAINT "bible_reading_session_pkey" TO "BibleReadingSession_pkey";
  END IF;

  -- ConversationState primary key
  IF to_regclass('"ConversationState"') IS NOT NULL
     AND EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'conversation_state_pkey')
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ConversationState_pkey') THEN
    ALTER TABLE "ConversationState" RENAME CONSTRAINT "conversation_state_pkey" TO "ConversationState_pkey";
  END IF;

  -- DebugRun primary key
  IF to_regclass('"DebugRun"') IS NOT NULL
     AND EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'debug_run_pkey')
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'DebugRun_pkey') THEN
    ALTER TABLE "DebugRun" RENAME CONSTRAINT "debug_run_pkey" TO "DebugRun_pkey";
  END IF;

  -- PipelineArtifact primary key
  IF to_regclass('"PipelineArtifact"') IS NOT NULL
     AND EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'pipeline_artifact_pkey')
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PipelineArtifact_pkey') THEN
    ALTER TABLE "PipelineArtifact" RENAME CONSTRAINT "pipeline_artifact_pkey" TO "PipelineArtifact_pkey";
  END IF;

  -- PipelineVault primary key
  IF to_regclass('"PipelineVault"') IS NOT NULL
     AND EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'pipeline_vault_pkey')
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PipelineVault_pkey') THEN
    ALTER TABLE "PipelineVault" RENAME CONSTRAINT "pipeline_vault_pkey" TO "PipelineVault_pkey";
  END IF;

  -- UserLifeContext primary key
  IF to_regclass('"UserLifeContext"') IS NOT NULL
     AND EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_life_context_pkey')
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'UserLifeContext_pkey') THEN
    ALTER TABLE "UserLifeContext" RENAME CONSTRAINT "user_life_context_pkey" TO "UserLifeContext_pkey";
  END IF;

  -- UserPreferences primary key
  IF to_regclass('"UserPreferences"') IS NOT NULL
     AND EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_preferences_pkey')
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'UserPreferences_pkey') THEN
    ALTER TABLE "UserPreferences" RENAME CONSTRAINT "user_preferences_pkey" TO "UserPreferences_pkey";
  END IF;
END $$;

-- -----------------------------
-- Drop legacy constraints/indexes (safe when absent)
-- -----------------------------
ALTER TABLE IF EXISTS "BibleReadingSession" DROP CONSTRAINT IF EXISTS "bible_reading_session_artifactId_fkey";
DROP INDEX IF EXISTS "bible_reading_session_artifactId_key";
DROP INDEX IF EXISTS "bible_reading_session_userId_bookId_endedAt_idx";

-- -----------------------------
-- Align table shapes
-- -----------------------------
-- BibleReadingSession: drop legacy location/completion columns (DESTRUCTIVE)
ALTER TABLE IF EXISTS "BibleReadingSession"
  DROP COLUMN IF EXISTS "artifactId",
  DROP COLUMN IF EXISTS "bookId",
  DROP COLUMN IF EXISTS "bookName",
  DROP COLUMN IF EXISTS "chapter",
  DROP COLUMN IF EXISTS "chapterId",
  DROP COLUMN IF EXISTS "completionStatus",
  DROP COLUMN IF EXISTS "translation",
  DROP COLUMN IF EXISTS "verseEnd",
  DROP COLUMN IF EXISTS "verseStart",
  DROP COLUMN IF EXISTS "versesVisibleCount";

-- ChatMessage / ChatSession timestamp precision alignment
ALTER TABLE IF EXISTS "ChatMessage" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3);

ALTER TABLE IF EXISTS "ChatSession"
  ALTER COLUMN "startedAt" SET DATA TYPE TIMESTAMP(3),
  ALTER COLUMN "endedAt" SET DATA TYPE TIMESTAMP(3),
  ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3),
  ALTER COLUMN "updatedAt" DROP DEFAULT,
  ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(3);

-- UserMemoryState updatedAt drop default (safe even if already none)
ALTER TABLE IF EXISTS "UserMemoryState" ALTER COLUMN "updatedAt" DROP DEFAULT;

-- UserRollup timestamp precision alignment
ALTER TABLE IF EXISTS "UserRollup"
  ALTER COLUMN "generatedAtUtc" SET DATA TYPE TIMESTAMP(3),
  ALTER COLUMN "expiresAt" SET DATA TYPE TIMESTAMP(3);

-- -----------------------------
-- Create missing tables (fixes P2021 for /api/chat tool)
-- -----------------------------
CREATE TABLE IF NOT EXISTS "BibleReadingSessionSegment" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "sessionId" TEXT NOT NULL,
  "segmentId" TEXT NOT NULL,
  "bookId" TEXT NOT NULL,
  "bookName" TEXT,
  "chapterId" TEXT,
  "chapter" INTEGER NOT NULL,
  "translation" TEXT NOT NULL,
  "startedAt" TIMESTAMP(3) NOT NULL,
  "endedAt" TIMESTAMP(3) NOT NULL,
  "durationSeconds" INTEGER NOT NULL,
  "readRanges" TEXT[],
  "source" TEXT NOT NULL DEFAULT 'ios',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "BibleReadingSessionSegment_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "BibleChapterDailyRollup" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "bookId" TEXT NOT NULL,
  "bookName" TEXT,
  "chapterId" TEXT,
  "chapter" INTEGER NOT NULL,
  "translation" TEXT NOT NULL,
  "durationSeconds" INTEGER NOT NULL DEFAULT 0,
  "completionStatus" JSONB,
  "readRanges" TEXT[],
  "localDate" TEXT NOT NULL,
  "timeZone" TEXT NOT NULL,
  "firstReadAt" TIMESTAMP(3),
  "lastReadAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "BibleChapterDailyRollup_pkey" PRIMARY KEY ("id")
);

-- -----------------------------
-- Indexes (idempotent)
-- -----------------------------
CREATE INDEX IF NOT EXISTS "BibleReadingSessionSegment_userId_sessionId_endedAt_idx"
  ON "BibleReadingSessionSegment" ("userId", "sessionId", "endedAt");

CREATE INDEX IF NOT EXISTS "BibleReadingSessionSegment_userId_sessionId_bookId_chapter_idx"
  ON "BibleReadingSessionSegment" ("userId", "sessionId", "bookId", "chapter");

CREATE UNIQUE INDEX IF NOT EXISTS "BibleReadingSessionSegment_userId_segmentId_key"
  ON "BibleReadingSessionSegment" ("userId", "segmentId");

CREATE INDEX IF NOT EXISTS "BibleChapterDailyRollup_userId_lastReadAt_idx"
  ON "BibleChapterDailyRollup" ("userId", "lastReadAt");

CREATE INDEX IF NOT EXISTS "BibleChapterDailyRollup_userId_bookId_chapter_idx"
  ON "BibleChapterDailyRollup" ("userId", "bookId", "chapter");

CREATE UNIQUE INDEX IF NOT EXISTS "BibleChapterDailyRollup_userId_bookId_chapter_localDate_key"
  ON "BibleChapterDailyRollup" ("userId", "bookId", "chapter", "localDate");

-- -----------------------------
-- Rename foreign key constraints (best-effort; names only)
-- -----------------------------
DO $$
BEGIN
  IF to_regclass('"Artifact"') IS NOT NULL
     AND EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'artifact_groupId_fkey')
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Artifact_groupId_fkey') THEN
    ALTER TABLE "Artifact" RENAME CONSTRAINT "artifact_groupId_fkey" TO "Artifact_groupId_fkey";
  END IF;

  IF to_regclass('"Artifact"') IS NOT NULL
     AND EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'artifact_userId_fkey')
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Artifact_userId_fkey') THEN
    ALTER TABLE "Artifact" RENAME CONSTRAINT "artifact_userId_fkey" TO "Artifact_userId_fkey";
  END IF;

  IF to_regclass('"ArtifactEdge"') IS NOT NULL
     AND EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'artifact_edge_fromId_fkey')
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ArtifactEdge_fromId_fkey') THEN
    ALTER TABLE "ArtifactEdge" RENAME CONSTRAINT "artifact_edge_fromId_fkey" TO "ArtifactEdge_fromId_fkey";
  END IF;

  IF to_regclass('"ArtifactEdge"') IS NOT NULL
     AND EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'artifact_edge_toId_fkey')
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ArtifactEdge_toId_fkey') THEN
    ALTER TABLE "ArtifactEdge" RENAME CONSTRAINT "artifact_edge_toId_fkey" TO "ArtifactEdge_toId_fkey";
  END IF;

  IF to_regclass('"ArtifactEmbedding"') IS NOT NULL
     AND EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'artifact_embedding_artifactId_fkey')
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ArtifactEmbedding_artifactId_fkey') THEN
    ALTER TABLE "ArtifactEmbedding" RENAME CONSTRAINT "artifact_embedding_artifactId_fkey" TO "ArtifactEmbedding_artifactId_fkey";
  END IF;

  IF to_regclass('"BibleReadingProgress"') IS NOT NULL
     AND EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'bible_reading_progress_userId_fkey')
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'BibleReadingProgress_userId_fkey') THEN
    ALTER TABLE "BibleReadingProgress" RENAME CONSTRAINT "bible_reading_progress_userId_fkey" TO "BibleReadingProgress_userId_fkey";
  END IF;

  IF to_regclass('"BibleReadingSession"') IS NOT NULL
     AND EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'bible_reading_session_userId_fkey')
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'BibleReadingSession_userId_fkey') THEN
    ALTER TABLE "BibleReadingSession" RENAME CONSTRAINT "bible_reading_session_userId_fkey" TO "BibleReadingSession_userId_fkey";
  END IF;

  IF to_regclass('"ConversationState"') IS NOT NULL
     AND EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'conversation_state_userId_fkey')
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ConversationState_userId_fkey') THEN
    ALTER TABLE "ConversationState" RENAME CONSTRAINT "conversation_state_userId_fkey" TO "ConversationState_userId_fkey";
  END IF;

  IF to_regclass('"UserLifeContext"') IS NOT NULL
     AND EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_life_context_userId_fkey')
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'UserLifeContext_userId_fkey') THEN
    ALTER TABLE "UserLifeContext" RENAME CONSTRAINT "user_life_context_userId_fkey" TO "UserLifeContext_userId_fkey";
  END IF;

  IF to_regclass('"UserPreferences"') IS NOT NULL
     AND EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_preferences_userId_fkey')
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'UserPreferences_userId_fkey') THEN
    ALTER TABLE "UserPreferences" RENAME CONSTRAINT "user_preferences_userId_fkey" TO "UserPreferences_userId_fkey";
  END IF;
END $$;

-- -----------------------------
-- Add missing foreign keys (idempotent)
-- -----------------------------
DO $$
BEGIN
  IF to_regclass('"BibleReadingSessionSegment"') IS NOT NULL
     AND to_regclass('"User"') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'BibleReadingSessionSegment_userId_fkey') THEN
    ALTER TABLE "BibleReadingSessionSegment"
      ADD CONSTRAINT "BibleReadingSessionSegment_userId_fkey"
      FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;

  IF to_regclass('"BibleReadingSessionSegment"') IS NOT NULL
     AND to_regclass('"BibleReadingSession"') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'BibleReadingSessionSegment_userId_sessionId_fkey') THEN
    ALTER TABLE "BibleReadingSessionSegment"
      ADD CONSTRAINT "BibleReadingSessionSegment_userId_sessionId_fkey"
      FOREIGN KEY ("userId", "sessionId") REFERENCES "BibleReadingSession"("userId", "sessionId") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;

  IF to_regclass('"BibleChapterDailyRollup"') IS NOT NULL
     AND to_regclass('"User"') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'BibleChapterDailyRollup_userId_fkey') THEN
    ALTER TABLE "BibleChapterDailyRollup"
      ADD CONSTRAINT "BibleChapterDailyRollup_userId_fkey"
      FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

-- -----------------------------
-- Rename indexes (idempotent)
-- -----------------------------
ALTER INDEX IF EXISTS "artifact_groupId_type_createdAt_idx" RENAME TO "Artifact_groupId_type_createdAt_idx";
ALTER INDEX IF EXISTS "artifact_sessionId_idx" RENAME TO "Artifact_sessionId_idx";
ALTER INDEX IF EXISTS "artifact_status_createdAt_idx" RENAME TO "Artifact_status_createdAt_idx";
ALTER INDEX IF EXISTS "artifact_userId_type_createdAt_idx" RENAME TO "Artifact_userId_type_createdAt_idx";
ALTER INDEX IF EXISTS "artifact_edge_fromId_relation_idx" RENAME TO "ArtifactEdge_fromId_relation_idx";
ALTER INDEX IF EXISTS "artifact_edge_toId_relation_idx" RENAME TO "ArtifactEdge_toId_relation_idx";
ALTER INDEX IF EXISTS "artifact_embedding_artifactId_model_key" RENAME TO "ArtifactEmbedding_artifactId_model_key";
ALTER INDEX IF EXISTS "artifact_embedding_model_idx" RENAME TO "ArtifactEmbedding_model_idx";
ALTER INDEX IF EXISTS "bible_reading_progress_userId_bookId_key" RENAME TO "BibleReadingProgress_userId_bookId_key";
ALTER INDEX IF EXISTS "bible_reading_progress_userId_updatedAt_idx" RENAME TO "BibleReadingProgress_userId_updatedAt_idx";
ALTER INDEX IF EXISTS "bible_reading_session_userId_endedAt_idx" RENAME TO "BibleReadingSession_userId_endedAt_idx";
ALTER INDEX IF EXISTS "bible_reading_session_userId_sessionId_key" RENAME TO "BibleReadingSession_userId_sessionId_key";
ALTER INDEX IF EXISTS "conversation_state_conversationId_key" RENAME TO "ConversationState_conversationId_key";
ALTER INDEX IF EXISTS "conversation_state_userId_idx" RENAME TO "ConversationState_userId_idx";
ALTER INDEX IF EXISTS "pipeline_artifact_expiresAt_idx" RENAME TO "PipelineArtifact_expiresAt_idx";
ALTER INDEX IF EXISTS "pipeline_artifact_runId_stage_key" RENAME TO "PipelineArtifact_runId_stage_key";
ALTER INDEX IF EXISTS "pipeline_artifact_traceId_idx" RENAME TO "PipelineArtifact_traceId_idx";
ALTER INDEX IF EXISTS "pipeline_artifact_userId_createdAt_idx" RENAME TO "PipelineArtifact_userId_createdAt_idx";
ALTER INDEX IF EXISTS "pipeline_vault_expiresAt_idx" RENAME TO "PipelineVault_expiresAt_idx";
ALTER INDEX IF EXISTS "pipeline_vault_runId_stage_key" RENAME TO "PipelineVault_runId_stage_key";
ALTER INDEX IF EXISTS "user_life_context_expiresAt_idx" RENAME TO "UserLifeContext_expiresAt_idx";
ALTER INDEX IF EXISTS "user_life_context_userId_idx" RENAME TO "UserLifeContext_userId_idx";
ALTER INDEX IF EXISTS "user_life_context_userId_type_idx" RENAME TO "UserLifeContext_userId_type_idx";
ALTER INDEX IF EXISTS "user_preferences_userId_key" RENAME TO "UserPreferences_userId_key";
ALTER INDEX IF EXISTS "UserRollup_userId_windowEndUtc_desc_idx" RENAME TO "UserRollup_userId_windowEndUtc_idx";

